// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_QwQ_BBEHpDAx4uI_acIl-AIQ75PNV2U',
    appId: '1:1009761941556:android:e8fff156e7649e66c9f261',
    messagingSenderId: '1009761941556',
    projectId: 'phone-auth-283f4',
    storageBucket: 'phone-auth-283f4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEXLBln3qOxRnyNL86vhW6bXTBiQBz-Ls',
    appId: '1:1009761941556:ios:cf9c7738ce32fdfec9f261',
    messagingSenderId: '1009761941556',
    projectId: 'phone-auth-283f4',
    storageBucket: 'phone-auth-283f4.appspot.com',
    iosClientId: '1009761941556-9gs3hnu90b44ebhpuvdeaaebsomai11e.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterLab',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3UL6GEyMNYVb3u-by_CzdIYsx81xnl8s',
    appId: '1:1009761941556:web:ed78c416694bd425c9f261',
    messagingSenderId: '1009761941556',
    projectId: 'phone-auth-283f4',
    authDomain: 'phone-auth-283f4.firebaseapp.com',
    storageBucket: 'phone-auth-283f4.appspot.com',
  );
}
